### ISSUE TITLE
Calculation of inter-rater reliability

### ISSUE THREAD

**Issue by amitsaha** [JCCKwong/APPRAISE-AI#1]
Hi @JCCKwong thanks for providing the excel sheet for score calculation.

I was wondering how can we also calculate the inter-rater and intrarater reliability? (Table 3.  Interrater and Intrarater Reliability of APPRAISE-AI Items, Domains, and Overall Score Determined by ICCs)

**Comment by JCCKwong** [comment]
Hi there, ICCs were calculated with 2-way random effects, absolute agreement, and single measurement. You can calculate this using a variety of tools (MedCalc, SPSS, Stata). There is also a python package _pingouin_ with an intraclass_corr function (https://pingouin-stats.org/build/html/generated/pingouin.intraclass_corr.html). Hope this helps.
